testing/shared/src/main/scala/io/chrisdavenport/log4cats/testing/TestingLogger.scala
Adding properties here makes it easier to assert that a given message was logged without needing to care about which level it was logged at.
=> Add properties to LogMessage trait

build.sbt
Also `better-monadic-for` because I can't see a reason not too in functional libs.
=> Update Scala Version to 2.12.6

README.md
Self-explanatory, `flatMap` was misspelled as `flatTap`
=> Fixes a small typo in the examples

core/shared/src/main/scala/io/chrisdavenport/log4cats/MDCLogger.scala, core/shared/src/main/scala/io/chrisdavenport/log4cats/SelfAwareLogger.scala, core/shared/src/main/scala/io/chrisdavenport/log4cats/SelfAwareMDCLogger.scala, log4s/shared/src/main/scala/io/chrisdavenport/log4cats/log4s/Log4sLogger.scala, slf4j/src/main/scala/io/chrisdavenport/log4cats/slf4j/Slf4jLogger.scala, testing/shared/src/main/scala/io/chrisdavenport/log4cats/testing/TestingLogger.scala
This proposes an alternative hierarchical algebra
```
Logger ----------
|                 \
SelfAwareLogger    MDCLogger
|                 /
MDCSelfAwareLogger
```
=> Hierarchical Logging Algebras

core/shared/src/main/scala/io/chrisdavenport/log4cats/SelfAwareMDCLogger.scala, core/shared/src/main/scala/io/chrisdavenport/log4cats/SelfAwareStructuredLogger.scala, core/shared/src/main/scala/io/chrisdavenport/log4cats/StructuredLogger.scala, slf4j/src/main/scala/io/chrisdavenport/log4cats/slf4j/Slf4jLogger.scala
Just a name change as MDC is something more specific, as this takes a context, not necessarily using injection, and applies it to the log messages.
=> Switch from MDC to StructuredLogger name

core/shared/src/main/scala/io/chrisdavenport/log4cats/ErrorLogger.scala, core/shared/src/main/scala/io/chrisdavenport/log4cats/Logger.scala, core/shared/src/main/scala/io/chrisdavenport/log4cats/MessageLogger.scala, core/shared/src/main/scala/io/chrisdavenport/log4cats/StructuredLogger.scala
Addresses a way of dealing with #44, so now we have a concrete solution.
=> Structure Hierarchy and Structured Logger Modification Function

cats/extras/shared/src/main/scala/io/chrisdavenport/log4cats/extras/LogLevel.scala, cats/extras/shared/src/main/scala/io/chrisdavenport/log4cats/extras/LogMessage.scala, cats/extras/shared/src/main/scala/io/chrisdavenport/log4cats/extras/WriterLogger.scala
For all those situations you want pure logging.
This also provides a run method, so whenever you return to a place with an effectful logger you can make the transformation quickly and efficiently.
=> Add Writer logger

cats/slf4j-internal/src/main/scala/io/chrisdavenport/log4cats/slf4j/internal/LoggerMacros.scala, cats/slf4j-internal/src/main/scala/io/chrisdavenport/log4cats/slf4j/internal/Slf4jLoggerInternal.scala, cats/slf4j/src/main/scala/io/chrisdavenport/log4cats/slf4j/Slf4jLogger.scala, cats/slf4j/src/test/scala/io/chrisdavenport/log4cats/slf4j/Slf4jLoggerMacroCompilationTests.scala
Fix `create` macros without code duplication and static annotations via a bundle.
I also added a few compilation tests. They don't check the name of the logger, but only validate quasiquotes.
=> Fix Slf4jLogger.create

cats/extras/shared/src/main/scala/io/chrisdavenport/log4cats/extras/WriterTLogger.scala
Here's an implementation of a `WriterT` logger (see #80). I based myself on how the current `Writer` logger is implemented.
I went through a handful of iterations and I'm still not sure if it's correct (it compiles). Especially, `run: WriterT[F, G[LogMessage], ?] ~> F` seems too constrained. I tried implementation it with the shape `WriterT[F, G[LogMessage], ?] ~> H` but couldn't.
=> Add WriterT logger

.travis.yml
JDK 8 is good, but JDK 11 is latest LTS version, so it would be good to test against them both.
As JDK 12 doesn't introduce anything heavily incompatible with JDK 11, it seems good enough to test against latest JDK release.
=> test against OpenJDK 12

build.sbt
`github4s` is not used directly in this project.
=> Remove dependency on github4s

testing/shared/src/main/scala/io/chrisdavenport/log4cats/testing/StructuredTestingLogger.scala
Following up on the Gitter chat in December, this PR adds a StructuredTestingLogger that provides a way to easily test structured logging. It is fairly simple. There is one point that might merit discussion. The log message case classes have a default for the ctx parameter such as:
```
final case class TRACE(message: String, throwOpt: Option[Throwable], ctx: Map[String, String] = Map.empty) extends LogMessage
```
This means that in classes where the context is missing in many cases, it makes it easier to test without explicitly providing Map.empty each time. The option is there to also provide a default for the throwOpt, so the tests only have to provide the mandatory message. This has the advantage that is to easier to read, but the disadvantage that it is 1) less explict, 2) …
=> Add the StructuredTestingLogger

core/shared/src/main/scala/org/typelevel/log4cats/extras/LogLevel.scala
I have this in my codebase, figured it makes sense to push upstream.
Do we want it to match the output of `show` at all?
=> Add a `LogLevel.fromString` method

core/shared/src/main/scala/org/typelevel/log4cats/SelfAwareStructuredLogger.scala, core/shared/src/main/scala/org/typelevel/log4cats/StructuredLogger.scala
Add ability to modify context, similar to `Logger.withModifiedString`
Example: mask some sensitive structure field values
```scala
val currentLogger: StructuredLogger[F] = ???
val maskRe = "(?<=.{3}).(?=[^@]*?@)".r
val hideEmailLogger = StructuredLogger.withModifiedContext(currentLogger) {
ctx => ctx.get("clientEmail").fold(ctx)(
email => ctx.updated("clientEmail", maskRe.replaceAllIn(email, "*"))
)
}
```
=> Add withModifiedContext to StructuredLogger

slf4j/src/main/scala-2/org/typelevel/log4cats/slf4j/internal/GetLoggerMacros.scala
Binary breaking, but not public facing.
=> Remove unused WeakTypeTag constraint

.github/workflows/ci.yml, CHANGELOG.md, build.sbt, project/build.properties
I think this is everything we need to get 2.0.1 w/ Scala 3.0.0-RC2 out the door.
Created by merging #418 into this one.
So if something's wrong with that PR, then we should drop this one and retry :sweat_smile:
=> Prepare release 2.0.1

core/shared/src/main/scala/org/typelevel/log4cats/SelfAwareLogger.scala, core/shared/src/main/scala/org/typelevel/log4cats/SelfAwareStructuredLogger.scala, core/shared/src/main/scala/org/typelevel/log4cats/StructuredLogger.scala, core/shared/src/test/scala/org/typelevel/log4cats/extras/syntax/LoggerSyntaxCompilation.scala
`Logger[F]` defined the method ` def withModifiedString(f: String => String): Logger[F]`
But subclasses of `Logger[F]` did not override it, leading to inconsistencies that are irksome at best:
```scala
val logger: SelfAwareStructuredLogger[IO] = ???
// does not compile because the method would return only Logger[IO]
val specialLogger: SelfAwareStructuredLogger[IO] = logger.withModifiedString(identity)
```
Now it's fixed.
=> Add missing `withModifiedString` overrides in `Logger[F]` subclasses

build.sbt
Removes redundant `.toSeq` and fixes deprecation warning of `sbtcrossproject.crossProject`.
=> A tiny `build.sbt` clean-up

README.md, core/shared/src/main/scala/org/typelevel/log4cats/syntax/package.scala, docs/src/main/mdoc/index.md
This adds syntax that allows logging in that way:
```scala
def log[F[_]: Sync: Logger] = 
for {
result1 <- successComputation[F]
_ <- info"First result is $result1"
_ <- errorComputation[F].onError(_ => error"We got an error!")
} yield ()
```
=> Add syntax for the `Logger`

.github/workflows/ci.yml, build.sbt, core/shared/src/main/scala/org/typelevel/log4cats/syntax/package.scala
The build was creating headers, but not checking headers.  This resulted in a diff, which bumped the version past the tag and resulted in a resolution failure on MiMa.  Cool.
I took a conservative approach and did not port to sbt-typelevel.
=> Fixes for log4cats-1.5

.github/workflows/ci.yml, build.sbt
Includes a bump of the base version to 2.2 in advance of the forthcoming tag.
=> Merge after v1.5.1

.github/workflows/ci.yml, .scalafmt.conf, build.sbt, docs/Gemfile, docs/index.md, project/plugins.sbt, slf4j/src/main/scala-3/org/typelevel/log4cats/slf4j/Slf4jLogger.scala, slf4j/src/main/scala-3/org/typelevel/log4cats/slf4j/internal/GetLoggerMacros.scala
Yeah yeah I know, this needs a backport to the other branch as well.
=> Migrate to sbt-typelevel

.github/workflows/ci.yml, .scalafmt.conf, build.sbt, docs/Gemfile, docs/src/main/mdoc/index.md, project/plugins.sbt, slf4j/src/main/scala-3/org/typelevel/log4cats/slf4j/Slf4jLogger.scala, slf4j/src/main/scala-3/org/typelevel/log4cats/slf4j/internal/GetLoggerMacros.scala
=> Migrate to `sbt-typelevel` in `series/1.x`

.scala-steward.conf
Updates of these artifacts will come from `series/1.x`.
=> Add artifact updates ignoring for Scala Steward

.scala-steward.conf
At the moment, log4cats has the same version of ScalaJS for both supported branches. I think this will continue, so here is this PR. log4cats will get updates of ScalaJS from `series/1.x`.
=> Ignore ScalaJS updates

build.sbt
should close https://github.com/typelevel/log4cats/issues/643
=> slf4j depends on core jvm, not core js

build.sbt
=> slf4j depends on core jvm for `series/1.x`

README.md, core/shared/src/main/scala/org/typelevel/log4cats/LoggerFactory.scala, docs/index.md
These docs are based on work made by @lorandszakacs in https://github.com/typelevel/log4cats/pull/421. So all credits go to them.
This covers a little part of the `LoggerFactory`, a basic functionality at most. It'd be great to complete it subsequently.
=> Add `LoggerFactory` docs

.scala-steward.conf
Hopefully the last from this branch.
I rolled back scalafmt-3.5.3, which wasn't on main yet, and has caused problems on other projects.
I also removed updates.ignore, as the 1.x branch will be removed from Scala Steward.
=> Merge 1.6.0

core/shared/src/main/scala/org/typelevel/log4cats/LoggerFactory.scala, core/shared/src/test/scala/org/typelevel/log4cats/extras/syntax/LoggerFactorySyntaxCompilation.scala
I've been playing around with Natchez and natchez-extras-log4cats. This proved to be a required step to use LoggerFactory rather than instantiating a Kleisli logger and passing around explicitly/implicitly.
I would have applied this to LoggerFactoryGen but with the override type I struggled, I think you would need to lift it into the typeclass signature, but suggestions welcome.
=> Add LoggerFactory.mapK

build.sbt
At least because of the Scala 3 upgrade in #664.  Probably other reasons.
=> Base version is 2.4

build.sbt, core/shared/src/main/scala/org/typelevel/log4cats/PagingSelfAwareStructuredLogger.scala, testing/shared/src/test/scala/org/typelevel/log4cats/PagingSelfAwareStructuredLoggerTestRunner.scala
Fixes https://github.com/typelevel/log4cats/issues/677.
=> Use `UUIDGen` instead of `randomUUID()`

core/shared/src/main/scala/org/typelevel/log4cats/LoggerFactoryGen.scala, docs/index.md, slf4j/src/main/scala/org/typelevel/log4cats/slf4j/Slf4jFactory.scala, slf4j/src/main/scala/org/typelevel/log4cats/slf4j/package.scala, slf4j/src/test/scala/org/typelevel/log4cats/slf4j/Slf4jLoggerMacroCompilationTests.scala
See https://github.com/typelevel/log4cats/pull/681#issuecomment-1224535985. Since there is not one canonical `LoggerFactory` implementation, they should be passed explicitly, not implicitly.
Closes https://github.com/typelevel/log4cats/pull/681.
=> Deprecate implicit materialization of `Slf4jFactory`

README.md
Added a more beginner friendly example and explanation to the README to help them bridge the gap from vanilla logging to log4cats
=> Beginner Friendly Example in README

.github/workflows/ci.yml, build.sbt, js-console/src/main/scala/org/typelevel/log4cats/console/Console.scala, js-console/src/main/scala/org/typelevel/log4cats/console/ConsoleF.scala, js-console/src/main/scala/org/typelevel/log4cats/console/ConsoleLogger.scala, js-console/src/main/scala/org/typelevel/log4cats/console/ConsoleLoggerFactory.scala
A basic implementation to close #680 and make logging available on Scala.js.
=> implement ConsoleLogger for Scala.js

README.md, core/shared/src/main/scala/org/typelevel/log4cats/extras/LogMessage.scala, core/shared/src/main/scala/org/typelevel/log4cats/extras/README.md, core/shared/src/main/scala/org/typelevel/log4cats/extras/StructuredLogMessage.scala, core/shared/src/main/scala/org/typelevel/log4cats/extras/WriterLogger.scala, core/shared/src/main/scala/org/typelevel/log4cats/extras/WriterStructuredLogger.scala, core/shared/src/main/scala/org/typelevel/log4cats/extras/WriterTLogger.scala, core/shared/src/main/scala/org/typelevel/log4cats/extras/WriterTStructuredLogger.scala, testing/README.md
Adds `WriterStructuredLogger`  and `WriterTStructuredLogger` as equivalents of `WriterLogger` and `WriterTLogger`, respectively.
Implements #718
=> Add structured equivalents of Writer & WriterT loggers

noop/shared/src/main/scala/org/typelevel/log4cats/noop/NoOpFactory.scala, noop/shared/src/main/scala/org/typelevel/log4cats/noop/NoOpLogger.scala
=> Add strict evaluation option

slf4j/src/main/scala/org/typelevel/log4cats/slf4j/Slf4jLogger.scala, slf4j/src/main/scala/org/typelevel/log4cats/slf4j/internal/Slf4jLoggerInternal.scala
=> Blocker Slf4j Logger Backer

core/shared/src/main/scala/org/typelevel/log4cats/LoggerFactory.scala
Adds methods to return updated versions that configure the loggers they produce using `addContext` and `withModifiedString`.
This should make it easier to migrate from passing around a single `SelfAwareStructuredLogger` and using a `LoggerFactory`.
=> Quality of life updates for LoggerFactory

core/shared/src/main/scala/org/typelevel/log4cats/PagingSelfAwareStructuredLogger.scala
Changes the tag behavior for a few of the tags on the Paged logger. The current tags seem optimized for human readability, not machine analytics. These changes allow metrics and dashboards to be created off of the tags without having to do a lot of pre-processing. This basically adds a bit more data about sizing, and creates some tags for data currently only added to the log message itself.
- Introduce a new field `log_size_bytes` for the new behavior, while leaving the old tag alone and deprecating it. This way we don't break existing behavior. In a major release we could switch this.
- Log size should log the size of _this_ log message, not the whole log. This allows summing of `log_size_bytes` to reflect the total logged volume without multi-counting paged messages. This is important …
=> Analyzable tags

core/shared/src/main/scala/org/typelevel/log4cats/extras/DeferredLogMessage.scala, core/shared/src/main/scala/org/typelevel/log4cats/extras/LogLevel.scala, slf4j/src/main/scala/org/typelevel/log4cats/slf4j/internal/Slf4jLoggerInternal.scala, slf4j/src/test/scala/org/typelevel/log4cats/slf4j/internal/JTestLogger.java, slf4j/src/test/scala/org/typelevel/log4cats/slf4j/internal/Slf4jLoggerInternalSuite.scala
Updates the handling of the MDC in `Slf4jLogger` to resolve questions raised in #851 
Changes:
- Always clear the MDC before populating when logging with context
- Don't skip the MDC massaging when logging without context
Checks:
- laziness of `msg` parameter
- dispatch to log4j Logger messages
- MDC setup/restoration
- MDC recovery when exceptions happen during message creation
=> Fix MDC handling in Slf4jLogger

slf4j/src/main/scala/org/typelevel/log4cats/slf4j/Slf4jLogger.scala, slf4j/src/main/scala/org/typelevel/log4cats/slf4j/internal/Slf4jLoggerInternal.scala, slf4j/src/test/scala/org/typelevel/log4cats/slf4j/internal/JTestLogger.java, slf4j/src/test/scala/org/typelevel/log4cats/slf4j/internal/Slf4jLoggerInternalSuite.scala
One approach to enable functionality requested in #868 (see also discussion in #907)
> [!NOTE]
> This will mean doing `MCD` manipulation every time `isEnabled` is called, but I don't really see a way around that if we want to support this functionality.
=> Expose MDC to Slf4jLoggerInternal isEnabled
