src/main/scala/io/chrisdavenport/log4cats/Logger.scala
No need to worry about calculating strings we may never need.
=> Lazy Arguments

src/main/scala/io/chrisdavenport/log4cats/Logger.scala
=> Allow Access to What Logging is Enabled

CHANGELOG.md, build.sbt, testing/shared/src/main/scala/io/chrisdavenport/log4cats/testing/TestingLogger.scala
TestingLogger implemented which has a record of all logged messages.
Fixes #11
=> Adds Testing Project

LICENSE, build.sbt
Switch to Apache Licensing. 
@keirlawson has already agreed on #26 
This is just codifying that issue.
Fixes #26
=> Switch to Apache Licensing

CHANGELOG.md
This release includes upgrades from Scribe, a hierarchical algebra modification and an optimized slf4j-api implementation for log4cats that is the new recommended logger.
=> Release Notes for 0.0.5

README.md, build.sbt, docs/src/main/tut/index.md
Switch from Log4s to slf4j module for documentation.
=> Add Documentation Improvement On Using slf4j implementation

CHANGELOG.md, core/shared/src/main/scala/io/chrisdavenport/log4cats/SelfAwareLogger.scala, core/shared/src/main/scala/io/chrisdavenport/log4cats/SelfAwareStructuredLogger.scala, core/shared/src/main/scala/io/chrisdavenport/log4cats/StructuredLogger.scala
Forgot to add implicit summoning to the new hierarchy.
=> Fix Implicit Summoning Methods

CHANGELOG.md
Shows what was released. General changelog update.
=> Update ChangeLog For RC1

cats/extras/shared/src/main/scala/io/chrisdavenport/log4cats/extras/implicits.scala, cats/extras/shared/src/main/scala/io/chrisdavenport/log4cats/extras/syntax/loggersyntax.scala, cats/extras/shared/src/test/scala/io/chrisdavenport/log4cats/extras/syntax/LoggerSyntaxCompilation.scala
I was worried about implicit conflicts, however the test code compiled happily. Seems ok.
=> Add Implicit Syntax For Loggers mapK

.gitignore, .travis.yml, build.sbt, cats/extras/shared/src/main/scala/io/chrisdavenport/log4cats/extras/Translate.scala, cats/log4s/shared/src/main/scala/io/chrisdavenport/log4cats/log4s/Log4sLogger.scala, cats/noop/shared/src/main/scala/io/chrisdavenport/log4cats/noop/NoOpLogger.scala, cats/slf4j/src/main/scala/io/chrisdavenport/log4cats/slf4j/Slf4jLogger.scala, core/shared/src/main/scala/io/chrisdavenport/log4cats/SelfAwareStructuredLogger.scala, core/shared/src/main/scala/io/chrisdavenport/log4cats/StructuredLogger.scala, version.sbt
=> StructuredLogger modifications

cats/extras/shared/src/main/scala/io/chrisdavenport/log4cats/extras/Translate.scala, cats/noop/shared/src/main/scala/io/chrisdavenport/log4cats/noop/NoOpLogger.scala, cats/slf4j/src/main/scala/io/chrisdavenport/log4cats/slf4j/internal/LoggerMacros.scala, cats/slf4j/src/main/scala/io/chrisdavenport/log4cats/slf4j/internal/Slf4jLoggerInternal.scala, core/shared/src/main/scala/io/chrisdavenport/log4cats/SelfAwareStructuredLogger.scala, core/shared/src/main/scala/io/chrisdavenport/log4cats/StructuredLogger.scala
Adds ContextLogging options for Throwables
=> Additional Context Logging Methods for Throwables

cats/slf4j/src/main/scala/io/chrisdavenport/log4cats/slf4j/internal/Slf4jLoggerInternal.scala
Also changed the `try/finally` to use a `.guarantee`. Let
=> Factor out some repetition in slf4j logger internals

slf4j/src/main/scala/io/chrisdavenport/log4cats/slf4j/internal/Slf4jLoggerInternal.scala
Closes #187 
thanks @oleg-py for pointing out the problem. Indeed it was that.
I assume that the commit that introduced the bug was the one that removed an `F.suspend` from somewhere at some point. Can't recall exactly. Mind might be playing tricks.
=> Fix issue 187 — MDC — rewrite finalizer w/ F.guarantee

.travis.yml, build.sbt, slf4j/src/main/scala/io/chrisdavenport/log4cats/slf4j/Slf4jLogger.scala
- Scala 2.12.9
- cats 2.0.0-RC1
- cats-effect 2.0.0-RC1
- unique 2.0.0-RC1
- Add explicit scala-reflect dependency for slf4j module
=> Add Updates for RC

build.sbt, slf4j/src/main/scala/io/chrisdavenport/log4cats/slf4j/internal/Slf4jLoggerInternal.scala, slf4j/src/test/resources/logback.xml, slf4j/src/test/scala/io/chrisdavenport/log4cats/slf4j/internal/Slf4jLoggerInternalSpec.scala
=> Fix Context Being Set During Logging

slf4j/src/main/scala/io/chrisdavenport/log4cats/slf4j/internal/LoggerMacros.scala, slf4j/src/test/scala/io/chrisdavenport/log4cats/slf4j/Hygiene.scala, slf4j/src/test/scala/io/chrisdavenport/log4cats/slf4j/Slf4jLoggerMacroCompilationTests.scala
This is unlikely to cause real problems but should probably still be fixed.
=> Fix macro hygiene issue

core/shared/src/main/scala/io/chrisdavenport/log4cats/Logger.scala
@ChristopherDavenport Let me know if there are any issues with this. Library is great so far, but I end up making these instances in my projects so I figured it'd make more sense to contribute it here if you're okay with it.
=> Add implicits for EitherT and OptionT transformers

noop/shared/src/main/scala/org/typelevel/log4cats/noop/NoOpLogger.scala
=> add apply method to NoOpLogger

.github/workflows/ci.yml, build.sbt, slf4j/src/main/scala-2/org/typelevel/log4cats/slf4j/internal/GetLoggerMacros.scala
* cats-effect-2.4.0
* scala-2.13.5
* run CI on series/* branches
=> Update all the things

.github/workflows/ci.yml, build.sbt, project/build.properties
=> Update sbt 1.5.0, drop csbt, tiny build.sbt cleanup

.github/workflows/ci.yml, CHANGELOG.md, build.sbt, core/shared/src/main/scala/org/typelevel/log4cats/SelfAwareLogger.scala, core/shared/src/main/scala/org/typelevel/log4cats/SelfAwareStructuredLogger.scala, core/shared/src/main/scala/org/typelevel/log4cats/StructuredLogger.scala, core/shared/src/test/scala/org/typelevel/log4cats/extras/syntax/LoggerSyntaxCompilation.scala
I merged #432 into this one, effectively doing forward porting from `1.x` if we are to merge this PR into main.
=>  Scala 3.0.0-RC3 support for series 2.x

build.sbt
Unfortunately this fell through the cracks :sweat_smile:
=> Bump base version to 1.3.0

build.sbt
Merging the last of small build tweaks before we can release.
=> Forward port release 1.3 changes

.github/workflows/ci.yml, CHANGELOG.md, build.sbt, project/plugins.sbt
Forward porting Scala 3.0.0 support :partying_face:
=> Scala 3.0.0 support for series 2.x

core/shared/src/main/scala/org/typelevel/log4cats/Logger.scala, core/shared/src/test/scala/org/typelevel/log4cats/extras/syntax/LoggerSyntaxCompilation.scala
=> add instance for Logger[Kleisli[F, A, *]]

build.sbt, project/build.properties, project/plugins.sbt
=> Merge `series/1.x` into main

.scala-steward.conf
=> Pin Cats-Effect and Scala 3 version in the Steward conf

.scala-steward.conf
=> Rm trailing comma in the Steward config

README.md, docs/src/main/mdoc/index.md
=> Enhance docs a bit

README.md, core/shared/src/main/scala/org/typelevel/log4cats/syntax/package.scala, docs/src/main/mdoc/index.md
=> Merge `series/1.x` into `main`

.github/workflows/ci.yml, build.sbt
=> Publish site only from `main` branch

README.md
Of course I don't notice it until after my last PR was merged
=> Fixed unbalanced parentheses

core/shared/src/main/scala/org/typelevel/log4cats/LoggerFactory.scala, core/shared/src/test/scala/org/typelevel/log4cats/extras/syntax/LoggerFactorySyntaxCompilation.scala
Add implicit derivations for LoggerFactory, similar to the existing ones for Logger
- OptionT
- EitherT
- Kleisli
=> Add implicit derivations for LoggerFactory

.sbtopts
=> Add `.sbtopts`
